// src/views/homeview/xuanzeqi.vue
<template>
    <div>
        <van-button @click="showPopup">12313213</van-button>
        <van-popup v-model="show" position="bottom" :style="{ height: '30%' }">
            <van-area :area-list="areaList" columns-num = '2' />
        </van-popup>
    </div>
</template>

<script>
import { areaList } from '@vant/area-data';
export default {
    data() {
        return {
            show: false,
            areaList: Object.freeze(areaList),
        };
    },

    methods: {
        confirm(e){

        },
        showPopup() {
            this.show = true;
        },
    },
};
</script>

// src/views/homeview/xuanzeqi.jsx
import { areaList } from '@vant/area-data';
import styled from 'styled-components-vue';
const Wrapper = styled.div`
   
    `
export default {
  render() {
    return (
      <div>
        <van-popup
          v-model={this.popupVisible}
          position="bottom"
          style={{ height: '40%' }}
        >
          <van-area
            columns-num="2"
            confirm-button-text="完成"
            area-list={areaList}
            onConfirm={this.confirm}
          />
        </van-popup>
      </div>
    );
  },
  data() {
    return {
      popupVisible: true,
    };
  },
  methods: {
    confirm(e) {
      this.popupVisible = false;
      console.log(e);
    },
  },
};
